spring:
  application:
    name: tlias-web-management
    #数据库连接信息
  datasource:
    url: jdbc:mysql://localhost:3306/tlias
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  servlet:
    multipart:
      #最大单个文件大小
      max-file-size: 10MB
      #最大请求大小（包括所有文件和表单数据）
      max-request-size: 100MB

#Mybatis的相关配置
mybatis:
  #显示日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启驼峰命名映射开关
    map-underscore-to-camel-case: true
  #mapper-locations: classpath:mapper/*.xml

  #配置事务管理日志级别
logging:
  level:
    org.springframeword.jdbc.support.JdbcTransactionManager: debug

aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucketName: java-oo
    region: cn-beijing


pagehelper:
  helper-dialect: mysql
  reasonable: true  #合理化参数： 页码<=0 查询第一页，页码>=总页数查询最后一页
